name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - staging  # Specify branches you want to trigger the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Vercel Deploy Hook
      run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_4l7Sz9ZOzv3sybJBXu96ImyEpJB6/Pz2v58qHbO"  # Replace with your hook URL
